import localFont from 'next/font/local'
import classNames from "classnames";

import "./globals.css";
import 'normalize.css/normalize.css'
import '@glidejs/glide/dist/css/glide.core.css'

import Header from './layout/header';

const FN = localFont({
  src: [
    {
      path: './layout/fonts/fn/subset-FuturaNewBook-Reg.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './layout/fonts/fn/subset-FuturaNewExtraBold-Reg.woff',
      weight: '800',
      style: 'normal',
    }
  ]
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={classNames(FN.className)}>
        <Header />

        {children}
      </body>
    </html>
  );
}
